// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return android;
      case TargetPlatform.macOS:
        return android;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT4fDKJN5V0SUJIzTeqG-82HWmMJNbRCE',
    appId: '1:289154329629:web:408a324a82632086ff2af4',
    messagingSenderId: '289154329629',
    projectId: 'contact-app-nqsuki',
    authDomain: 'contact-app-nqsuki.firebaseapp.com',
    storageBucket: 'contact-app-nqsuki.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT4fDKJN5V0SUJIzTeqG-82HWmMJNbRCE',
    appId: '1:289154329629:android:408a324a82632086ff2af4',
    messagingSenderId: '289154329629',
    projectId: 'contact-app-nqsuki',
    storageBucket: 'contact-app-nqsuki.firebasestorage.app',
  );
}
